userid: FA47872
Credential:
    password: Roshini#2023
    LogginThroughToken: 0
    TokenFile: token.txt
    TwoFA: 35DJA64O535MR4452V45AOMNR7F66GV2
    vendor_code: FA47872_U
    api_secret: 1ac4b41c4521f165c9cdcc5e82b33b97
    imei: abcd1234
Algo_Setup: 
    TradeMode : Paper
    quantity : 50
    TradeSymbol : NIFTY
    option_lower_range : 180
    option_upper_range : 200
    OptionSnapShotTime : "9:25:00"
    EntryTime : "9:33:00"
    Trade_Squareoff_Time : "15:00:00"
    BuyAbove : 200
    Target_Point : 30
    SL_Point : 30